package math

import (
	"context"

	mathv1 "github.com/harrisoncramer/grpc-connect-http/apis/gen/math/v1" // generated by protoc-gen-go
)

type GrpcService struct {
	mathv1.UnimplementedMathServiceServer
}

func (s GrpcService) Add(ctx context.Context, req *mathv1.AddRequest) (*mathv1.AddResponse, error) {

	first := req.First
	second := req.Second

	return &mathv1.AddResponse{
		Result: first + second,
	}, nil
}

func NewGrpcService() *GrpcService {
	return &GrpcService{}
}
